[package]
    authors = ["ksgk1"]
    edition = "2024"
    name    = "immosaic"
    version = "0.1.0"

[[bin]]
    name = "immosaic"

[dependencies]
    image      = { version = "0.25.10", default-features = false, features = ["bmp", "jpeg", "png", "rayon", "serde", "webp"] }
    lexopt     = { version = "0.3.2" }
    rayon      = { version = "1.12.0" }
    serde      = { version = "1.0.229", default-features = false, features = ["derive"] }
    serde_json = { version = "1.0.151" }
    walkdir    = { version = "2.5.0" }

[lints.clippy]
    cast_possible_truncation = "allow"
    complexity               = { level = "deny", priority = -1 }
    correctness              = { level = "deny", priority = -1 }
    nursery                  = { level = "deny", priority = -1 }
    pedantic                 = { level = "deny", priority = -1 }
    perf                     = { level = "deny", priority = -1 }
    style                    = { level = "deny", priority = -1 }
    suspicious               = { level = "deny", priority = -1 }
    unwrap_used              = "deny"
