name: Build and Release with Cross

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  ARTEFACT_NAME: "immosaic"
  BINARY_NAME: "immosaic"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install musl-tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get purge man-db && sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package (Windows)
        if: matrix.target == 'x86_64-pc-windows-msvc'
        shell: pwsh
        run: |
          $version = if ("${{ github.ref }}".StartsWith("refs/tags/v")) { "${{ github.ref_name }}" } else { "${{ github.sha }}".Substring(0, 7) }
          New-Item -ItemType Directory -Path release -Force
          Copy-Item -Path "target\x86_64-pc-windows-msvc\release\$env:ARTEFACT_NAME.exe" -Destination "release\$env:BINARY_NAME-$version.exe"

      - name: Package (Linux)
        if: matrix.target != 'x86_64-pc-windows-msvc'
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            version="${{ github.ref_name }}"
          else
            version=$(echo "${{ github.sha }}" | cut -c1-7)
          fi
          mkdir -p release
          cp target/${{ matrix.target }}/release/$ARTEFACT_NAME release/$BINARY_NAME-$version-${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.target }}
          path: release/

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          path: release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/x86_64-unknown-linux-musl/${{ env.BINARY_NAME }}-${{ github.ref_name }}-x86_64-unknown-linux-musl
            release/x86_64-pc-windows-msvc/${{ env.BINARY_NAME }}-${{ github.ref_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
